### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by mcgema** [gusals3587/jumpcutterV2#13]
**macOS 10.13.6 (but this problem also happened in a Windows 10)**

OS:
python --version: 3.8.3

**I think I have all the requirements but it is not working.**

I run this command in the terminal:
python3 fast_video.py -h

Then it showed this:
Traceback (most recent call last):
  File "fast_video.py", line 14, in <module>
    silentSpeed = float(sys.argv[2])
IndexError: list index out of range**

What can I do to fix this?

**Comment by gusals3587** [comment]
JumpcutterV2 don’t have help doc, the github README is all the documentation the project has(apart from code comment)
