### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by ThatOneCalculator** [gusals3587/jumpcutterV2#14]
Hi! Your repo's name conflict with my repo's name https://github.com/thatonecalculator/pyjumpcutterv2 (made 2 years before this)

Do you think we could work something out for a slightly different naming scheme?

**Comment by ThatOneCalculator** [comment]
Can you like... say something @gusals3587 ?

**Comment by gusals3587** [comment]
well.. alright
tl;dr this project is pretty much abandoned (atleast by me). I had a clever idea about jumpcutter that may speed it up, made it, implemented it, and realized it's still not that usable. the speed up, while not negligible, is still not fast enough for media consumption.
the repo's name is not exactly in conflict, so I don't mind having similar naming scheme, you'll gonna need a catchier name if you want this to be usable for mainstream market anyway
