### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'output.wav'

### ISSUE THREAD

**Issue by nbhat000** [gusals3587/jumpcutterV2#3]
Trying to use this with the command "python fast_video.py P1022712.MP4 999999999999". I tried with the video file (P1022712.MP4) both in the jumpcutterV2-master folder and in the directory above, and both times I got the same error. How can I fix this? 

**THE ERROR **

`OpenCV: Couldn't read video stream from file "P1022712.MP4"
/bin/sh: ffmpeg: command not found
Traceback (most recent call last):
  File "fast_video.py", line 27, in <module>
    sampleRate, audioData = wavfile.read("output.wav")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'output.wav'`

**WHAT I TRIED**
I tried adding "./output.wav" to the first instance of this call 
(i.e. 
"extractAudio = "ffmpeg -i {} -ab 160k -ac 2 -ar 44100 -vn output.wav".format(videoFile)" _changed to_ 
"extractAudio = "ffmpeg -i {} -ab 160k -ac 2 -ar 44100 -vn ./output.wav".format(videoFile)") 
and it stopped throwing the error there.But then it proceeded to throw the error on the next instance of "output.wav" 
("sampleRate, audioData = wavfile.read("output.wav")"). 

What can I do to fix this? Really looking forward to using this - thanks for your work!

**Comment by gusals3587** [comment]
Oh.. sorry, I only tested my script on python 3, I’ll take a look, but can’t promise any update on this

On the other hand, it’ll be useful if you can give me a link to a video that’s causing the problem ( or some other video online that gives you the same error )

**Comment by gusals3587** [comment]
I also put the video file on the same directory that the fast_video.py and arrayWav.py resides in and execute the command there as well.

**Comment by boostem** [comment]
Also having this same issue. I haven't edited any of the code.

Working in virtualenv on Ubuntu 18.04. Only addons is pip install -r requirements.

only command being used is:
![image](https://user-images.githubusercontent.com/6678958/74265823-36d49a00-4cd1-11ea-8a99-28d3138a986a.png)

set chmod 777 video.mp4 as well, thought maybe it was a permissions thing.

However, a "spedup.mp4" is being created when running the command. it cannot be played though due to "the video not having any playable streams"

**Comment by gusals3587** [comment]
you don't seem to have ffmpeg, ffmpeg is supposed to create output.wav in the first step of the program
