### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by uberstar100** [gusals3587/jumpcutterV2#4]
Hi, where can I obtain cv2?
** Command(s) Ran**
fast_video.py

** Error log **
Traceback (most recent call last):
  File "C:\Users\JohnSmith\jumpcutterV2\fast_video.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by gusals3587** [comment]
pip3 install -r requirements.txt

edit: changed thanks to below comment

**Comment by hazi98** [comment]
Hi, just wanted to point out that if you have multiple Python versions in your system, use pip3 for installing the required packages since it uses python3

**Comment by uberstar100** [comment]
thx
