### ISSUE TITLE
faster_.\Lecture.mp4: No such file or directory 

### ISSUE THREAD

**Issue by yazdipour** [gusals3587/jumpcutterV2#7]
OS: Windows
python --version: 3.8.1

When running: `python fast_video.py .\Lecture.mp4 20`
This Error Happens: `Line 132: faster_.\Lecture.mp4: No such file or directory `

Didn't check but I guess same thing could happen in Linux `faster_./Lecture.mp4`

**Comment by gusals3587** [comment]
Why would a file have ./? Seems a bit too edge case for me

**Comment by yazdipour** [comment]
You can close the issue if it is not important but, adding `.\` is the default behavior of Autocomplete PowerShell in windows

**Comment by yazdipour** [comment]
One another reason why it is better to change the code:
If you try to address a video in a different directory like `python fast_video.py myDirectory\Lecture.mp4 10`, it's gonna throw exception `faster_myDirectory\Lecture.mp4: No such file or directory`

**Comment by gusals3587** [comment]
hmm.. now I feel like I want to get rid of shell commands entirely, but I guess I'll accept the alternative in case I never get around to doing it
